### ISSUE TITLE
твою мать хуярил каждый прохожий

### ISSUE THREAD

**Issue by BreadBSS** [eesdfdev/Brawl-Stars-decompiled-source#2]
сын шлюхи

**Comment by moonbrawl** [comment]
> сын шлюхи

го в попку по братски

**Comment by n1sebs** [comment]
___           ___                       ___     
    ___                   /  /\         /__/\          ___        /  /\    
   /  /\                 /  /:/         \  \:\        /  /\      /  /::\   
  /  /:/                /  /:/           \__\:\      /  /:/     /  /:/\:\  
 /__/::\               /  /:/  ___   ___ /  /::\    /  /:/     /  /:/  \:\ 
 \__\/\:\__           /__/:/  /  /\ /__/\  /:/\:\  /  /::\    /__/:/ \__\:\
    \  \:\/\          \  \:\ /  /:/ \  \:\/:/__\/ /__/:/\:\   \  \:\ /  /:/
     \__\::/           \  \:\  /:/   \  \::/      \__\/  \:\   \  \:\  /:/ 
     /__/:/             \  \:\/:/     \  \:\           \  \:\   \  \:\/:/  
     \__\/               \  \::/       \  \:\           \__\/    \  \::/   
                          \__\/         \__\/                     \__\/
